name: Parallel SpecFlow Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run tests in parallel containers
      run: docker-compose up --abort-on-container-exit --exit-code-from login_tests

    - name: Archive LivingDoc reports
      if: always()
      run: |
        if [ -d reports ]; then
          mkdir -p artifacts
          cp -r reports artifacts/reports
        else
          echo "No reports directory found. Skipping copy."
        fi

    - name: Upload reports as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: LivingDocReports
        path: artifacts/reports
